apiVersion: v1
kind: Service
metadata:
  name: website-service
  namespace: production
  labels:
    app: website
spec:
  type: LoadBalancer   # will create ELB on AWS
  selector:
    app: website
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
